# Use official Node.js LTS image
FROM node:24-alpine AS builder

WORKDIR /app
COPY . .
RUN npm install
RUN npm run build:server

WORKDIR /app/server

# Expose the port your NestJS app runs on (default 3001)
EXPOSE 3001

# Set NODE_ENV to production
ENV NODE_ENV=production

# Start the server
CMD ["node", "dist/main.js"]