version: '3.8'

services:
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: no
    ports:
      # LiveKit API and WebSocket port
      - "7800:7800"
      # LiveKit WebRTC port (UDP)
      - "7801:7801/udp"
      # LiveKit Prometheus metrics and HTTP dashboard (optional, for monitoring)
      - "8080:8080"
    environment:
      # These environment variables are typically for clients generating tokens,
      # not for the LiveKit server's internal key configuration.
      # The server's keys are now configured via livekit.yaml.
      # - LIVEKIT_API_KEY=devkey
      # - LIVEKIT_API_SECRET=secret
      - LIVEKIT_HOST=0.0.0.0
      - LIVEKIT_PORT=7800
      - LIVEKIT_WEBRTC_PORT=7801
    volumes:
      # Mount the livekit.yaml file into the container
      - ./livekit.yaml:/etc/livekit/livekit.yaml
    command:
      # Tell the LiveKit server to use the mounted config file
      - "--config"
      - "/etc/livekit/livekit.yaml"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
