version: "3.8"

services:
  rtmp-server:
    image: alqutami/rtmp-hls
    container_name: rtmp-server
    ports:
      - "1935:1935"
      - "8080:8080"
  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    restart: no
    ports:
      # LiveKit API and WebSocket port
      - "7800:7800"
      # LiveKit WebRTC port (UDP)
      - "7801:7801/udp"
    environment:
      - LIVEKIT_HOST=0.0.0.0
      - LIVEKIT_PORT=7800
      - LIVEKIT_WEBRTC_PORT=7801
    volumes:
      # Mount the livekit.yaml file into the container
      - ./livekit.yaml:/etc/livekit/livekit.yaml
    command:
      # Tell the LiveKit server to use the mounted config file
      - "--config"
      - "/etc/livekit/livekit.yaml"
    networks:
      - app-network
    depends_on:
      - redis
  
  livekit-egress:
    image: livekit/egress:latest
    container_name: livekit-egress
    restart: no
    environment:
      - EGRESS_CONFIG_FILE=/etc/livekit/egress.yaml
    networks:
      - app-network
    depends_on:
      - livekit-server
      - redis
    volumes:
      - ./livekit-egress.yaml:/etc/livekit/egress.yaml
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network
  

networks:
  app-network:
    driver: bridge
