version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx-default.conf:/etc/nginx/conf.d/default.conf
      - ./static-client:/var/www/static-client
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    network_mode: host
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./log/letsencrypt:/var/log/letsencrypt
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  backend:
    image: pablitar/dcl-tbs-backend
    container_name: dcl-tbs-backend
    environment:
      - LIVEKIT_HOST=http://localhost:7880
    network_mode: host

  livekit-server:
    image: livekit/livekit-server:latest
    container_name: livekit-server
    environment:
      - LIVEKIT_HOST=0.0.0.0
    volumes:
      # Mount the livekit.yaml file into the container
      - ./livekit.yaml:/etc/livekit/livekit.yaml
    command:
      # Tell the LiveKit server to use the mounted config file
      - "--config"
      - "/etc/livekit/livekit.yaml"
    depends_on:
      - redis
    network_mode: host
  
  livekit-egress:
    image: livekit/egress:latest
    container_name: livekit-egress
    ports:
      - "7980:7980"
    environment:
      - EGRESS_CONFIG_FILE=/etc/livekit/egress.yaml
    networks:
      - app-network
    depends_on:
      - livekit-server
      - redis
    volumes:
      - ./livekit-egress.yaml:/etc/livekit/egress.yaml
      - ./out:/out
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
